import Foundation

let tag = "v4.1.0"
let url = URL(string:
  "https://raw.githubusercontent.com/github/gemoji/\(tag)/db/emoji.json")!
let raw = try Data(contentsOf: url)

struct Entry: Decodable { let emoji: String?; let aliases: [String] }
let entries = try JSONDecoder().decode([Entry].self, from: raw)

var map: [String: String] = [:]
for e in entries {
  guard let emoji = e.emoji else { continue }
  for alias in e.aliases where map[alias] == nil { map[alias] = emoji }
}

// Deterministic, minified JSON (sorted keys) for a stable diff.
let enc = JSONEncoder()
enc.outputFormatting = [.sortedKeys, .withoutEscapingSlashes]
let json = String(data: try enc.encode(map), encoding: .utf8)!

let out = """
// Generated by Scripts/generate-aliases.swift from github/gemoji \(tag).
// Do not edit by hand; run `swift Scripts/generate-aliases.swift` to refresh.
let aliasesJSON = #\"\"\"
\(json)
\"\"\"#
"""
try (out + "\n").write(
  toFile: "Sources/EmojiToPNGCore/Aliases.generated.swift",
  atomically: true, encoding: .utf8)
print("wrote Sources/EmojiToPNGCore/Aliases.generated.swift (\(map.count) aliases)")
